src/Entity/Rezerwacja.php
<?php

namespace App\Entity;

use App\Repository\RezerwacjaRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RezerwacjaRepository::class)
 */
class Rezerwacja
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $numer_stolika;

    /**
     * @ORM\Column(type="integer")
     */
    private $licz_gosci;

    /**
     * @ORM\Column(type="datetime")
     */
    private $data;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numer_kontaktowy;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $imie_rezerwujacego;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nazwisko_rezerwujacego;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumerStolika(): ?int
    {
        return $this->numer_stolika;
    }

    public function setNumerStolika(int $numer_stolika): self
    {
        $this->numer_stolika = $numer_stolika;

        return $this;
    }

    public function getLiczGosci(): ?int
    {
        return $this->licz_gosci;
    }

    public function setLiczGosci(int $licz_gosci): self
    {
        $this->licz_gosci = $licz_gosci;

        return $this;
    }

    public function getData(): ?\DateTimeInterface
    {
        return $this->data;
    }

    public function setData(\DateTimeInterface $data): self
    {
        $this->data = $data;

        return $this;
    }

    public function getNumerKontaktowy(): ?string
    {
        return $this->numer_kontaktowy;
    }

    public function setNumerKontaktowy(string $numer_kontaktowy): self
    {
        $this->numer_kontaktowy = $numer_kontaktowy;

        return $this;
    }

    public function getImieRezerwujacego(): ?string
    {
        return $this->imie_rezerwujacego;
    }

    public function setImieRezerwujacego(string $imie_rezerwujacego): self
    {
        $this->imie_rezerwujacego = $imie_rezerwujacego;

        return $this;
    }

    public function getNazwiskoRezerwujacego(): ?string
    {
        return $this->nazwisko_rezerwujacego;
    }

    public function setNazwiskoRezerwujacego(string $nazwisko_rezerwujacego): self
    {
        $this->nazwisko_rezerwujacego = $nazwisko_rezerwujacego;

        return $this;
    }
}

src/Form/RezerwacjaType.php
<?php

namespace App\Form;

use App\Entity\Rezerwacja;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RezerwacjaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('numer_stolika')
            ->add('licz_gosci')
            ->add('data')
            ->add('numer_kontaktowy')
            ->add('imie_rezerwujacego')
            ->add('nazwisko_rezerwujacego')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Rezerwacja::class,
        ]);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'home')]
    public function index(): Response
    {
        return $this->render('three.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }

    #[Route('/rezerwacja3d', name: 'rezerwacja3d')]
    public function rez3d(): Response
    {
        return $this->render('rez3d.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }

    #[Route('/rezerwacja3d_mario_room', name: 'rezerwacja3d_mario_room')]
    public function rezerwacja3d_mario_room(): Response
    {
        return $this->render('rez3d_mario_room.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }

    #[Route('/rezerwacja3d_invaders_room', name: 'rezerwacja3d_invaders_room')]
    public function rezerwacja3d_invaders_room(): Response
    {
        return $this->render('rez3d_invaders_room.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }

}

src/Controller/RezerwacjaController.php
<?php

namespace App\Controller;

use App\Entity\Rezerwacja;
use App\Form\RezerwacjaType;
use App\Repository\RezerwacjaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/rezerwacje')]
class RezerwacjaController extends AbstractController
{
    #[Route('/', name: 'rezerwacja_index', methods: ['GET'])]
    public function index(RezerwacjaRepository $rezerwacjaRepository): Response
    {
        return $this->render('rezerwacja/index.html.twig', [
            'rezerwacjas' => $rezerwacjaRepository->findAll(),
        ]);
    }

    #[Route('/nowa_rezerwacja', name: 'nowa_rezerwacja', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $rezerwacja = new Rezerwacja();
        $form = $this->createForm(RezerwacjaType::class, $rezerwacja);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($rezerwacja);
            $entityManager->flush();

            return $this->redirectToRoute('rezerwacja_index');
        }

        return $this->render('rezerwacja/new.html.twig', [
            'rezerwacja' => $rezerwacja,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'rezerwacja_show', methods: ['GET'])]
    public function show(Rezerwacja $rezerwacja): Response
    {
        return $this->render('rezerwacja/show.html.twig', [
            'rezerwacja' => $rezerwacja,
        ]);
    }

    #[Route('/{id}/edytuj', name: 'rezerwacja_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Rezerwacja $rezerwacja): Response
    {
        $form = $this->createForm(RezerwacjaType::class, $rezerwacja);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('rezerwacja_index');
        }

        return $this->render('rezerwacja/edit.html.twig', [
            'rezerwacja' => $rezerwacja,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'rezerwacja_delete', methods: ['POST'])]
    public function delete(Request $request, Rezerwacja $rezerwacja): Response
    {
        if ($this->isCsrfTokenValid('delete'.$rezerwacja->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($rezerwacja);
            $entityManager->flush();
        }

        return $this->redirectToRoute('rezerwacja_index');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
      <meta charset="UTF-8" />
      <link rel="shortcut icon" type="image/svg" href="{{ asset('svg/icon.svg') }}"/>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>{% block title %}PixoBurgers{% endblock %}</title>

      {% block stylesheets %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      {% endblock %}

      {% block javascripts %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      {% endblock %}
    </head>

    <body>
      {% block body %}{% endblock %}
    </body>

</html>

templates/rez3d.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
  {{ parent() }}
  <link href="{{ asset('css/rez3d.css') }}" rel="stylesheet"/>
{% endblock %}

{% block body %}
<canvas id="bg">canvas</canvas>
  <main>
    <div id="here" style="display:none;">
      <a href="{{ path('nowa_rezerwacja') }}">
        <p id="option">Wynajmij ten stolik</p>
      </a>
    </div>
  </main>
{% endblock %}

{% block javascripts %}
  {{ parent() }}
  <script type="module" src="{{ asset('js/pokoj_wolf.js') }}">
  </script>
  <script type="module" src="{{ asset('js/controls_hdr.js') }}">
  </script>
{% endblock %}

templates/rez3d_invaders_room.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
  {{ parent() }}
  <link href="{{ asset('css/rez3d.css') }}" rel="stylesheet"/>
{% endblock %}

{% block body %}
<canvas id="bg">canvas</canvas>
  <main>
    <div id="here" style="display:none;">
      <a href="{{ path('nowa_rezerwacja') }}">
        <p id="option">Wynajmij stolik w tym pokoju (Pokój Invaders)</p>
      </a>

      <div id="kafelki">

        <div id="kafelek1">
          <a href="{{ path('rezerwacja3d') }}">
            <img src="{{ asset('pic/room_wolf_logo.svg') }}" alt="logo pokoju wolf 3d">
          </a>
        </div>

        <div id="kafelek2">
          <a href="{{ path('rezerwacja3d_mario_room') }}">
            <img src="{{ asset('pic/room_mario_logo.svg') }}" alt="logo pokoju mario">
          </a>
        </div>

        <div id="kafelek3">
          <a href="{{ path('rezerwacja3d_invaders_room') }}">
            <img src="{{ asset('pic/space_invaders_room_logo.svg') }}" alt="logo pokoju space invaders">
          </a>
        </div>

      </div>
    </div>
  </main>
{% endblock %}

{% block javascripts %}
  <!-- {{ parent() }} -->
  <script type="module" src="{{ asset('js/pokoj_invaders.js') }}">
  </script>
  <script type="module" src="{{ asset('js/controls_hdr.js') }}">
  </script>
{% endblock %}

templates/rez3d_mario_room.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
  {{ parent() }}
  <link href="{{ asset('css/rez3d.css') }}" rel="stylesheet"/>
{% endblock %}

{% block body %}
<canvas id="bg">canvas</canvas>
  <main>
    <div id="here" style="display:none;">
      <a href="{{ path('nowa_rezerwacja') }}">
        <p id="option">Wynajmij stolik w tym pokoju (Pokoj Mario)</p>
      </a>

      <div id="kafelki">

        <div id="kafelek1">
          <a href="{{ path('rezerwacja3d') }}">
            <img src="{{ asset('pic/room_wolf_logo.svg') }}" alt="logo pokoju wolf 3d">
          </a>
        </div>

        <div id="kafelek2">
          <a href="{{ path('rezerwacja3d_mario_room') }}">
            <img src="{{ asset('pic/room_mario_logo.svg') }}" alt="logo pokoju mario">
          </a>
        </div>

        <div id="kafelek3">
          <a href="{{ path('rezerwacja3d_invaders_room') }}">
            <img src="{{ asset('pic/space_invaders_room_logo.svg') }}" alt="logo pokoju space invaders">
          </a>
        </div>

      </div>
    </div>
  </main>
{% endblock %}

{% block javascripts %}
  <!-- {{ parent() }} -->
  <script type="module" src="{{ asset('js/pokoj_mario.js') }}">
  </script>
  <script type="module" src="{{ asset('js/controls_hdr.js') }}">
  </script>
{% endblock %}

templates/rezerwacja/_delete_form.html.twig
<form method="post" action="{{ path('rezerwacja_delete', {'id': rezerwacja.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ rezerwacja.id) }}">
    <button class="btn">Delete</button>
</form>

templates/rezerwacja/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/rezerwacja/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Rezerwacja{% endblock %}

{% block body %}
    <h1>Edit Rezerwacja</h1>

    {{ include('rezerwacja/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('rezerwacja_index') }}">back to list</a>

    {{ include('rezerwacja/_delete_form.html.twig') }}
{% endblock %}

templates/rezerwacja/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rezerwacja index{% endblock %}

{% block stylesheets %}  {% endblock %}

{% block body %}
    <h1 class="title_h1">Rezerwacja index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Numer_stolika</th>
                <th>Licz_gosci</th>
                <th>Data</th>
                <th>Numer_kontaktowy</th>
                <th>Imie_rezerwujacego</th>
                <th>Nazwisko_rezerwujacego</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for rezerwacja in rezerwacjas %}
            <tr>
                <td>{{ rezerwacja.id }}</td>
                <td>{{ rezerwacja.numerStolika }}</td>
                <td>{{ rezerwacja.liczGosci }}</td>
                <td>{{ rezerwacja.data ? rezerwacja.data|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ rezerwacja.numerKontaktowy }}</td>
                <td>{{ rezerwacja.imieRezerwujacego }}</td>
                <td>{{ rezerwacja.nazwiskoRezerwujacego }}</td>
                <td>
                    <a href="{{ path('rezerwacja_show', {'id': rezerwacja.id}) }}">show</a>
                    <a href="{{ path('rezerwacja_edit', {'id': rezerwacja.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('nowa_rezerwacja') }}">Create new</a>
{% endblock %}

templates/rezerwacja/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nowa Rezerwacja{% endblock %}

{% block stylesheet %}
  {{ parent() }}
  <link href="{{ asset('css/form_new.css') }}" rel="stylesheet"/>
{% endblock stylesheet %}

{% block body %}
    <h1>Podaj informacje dotyczące składanej rezerwacji</h1>

    {{ include('rezerwacja/_form.html.twig') }}

    <a href="{{ path('rezerwacja_index') }}">powrót</a>
{% endblock %}

templates/rezerwacja/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rezerwacja{% endblock %}

{% block body %}
    <h1>Rezerwacja</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ rezerwacja.id }}</td>
            </tr>
            <tr>
                <th>Numer_stolika</th>
                <td>{{ rezerwacja.numerStolika }}</td>
            </tr>
            <tr>
                <th>Licz_gosci</th>
                <td>{{ rezerwacja.liczGosci }}</td>
            </tr>
            <tr>
                <th>Data</th>
                <td>{{ rezerwacja.data ? rezerwacja.data|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Numer_kontaktowy</th>
                <td>{{ rezerwacja.numerKontaktowy }}</td>
            </tr>
            <tr>
                <th>Imie_rezerwujacego</th>
                <td>{{ rezerwacja.imieRezerwujacego }}</td>
            </tr>
            <tr>
                <th>Nazwisko_rezerwujacego</th>
                <td>{{ rezerwacja.nazwiskoRezerwujacego }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('rezerwacja_index') }}">back to list</a>

    <a href="{{ path('rezerwacja_edit', {'id': rezerwacja.id}) }}">edit</a>

    {{ include('rezerwacja/_delete_form.html.twig') }}
{% endblock %}

templates/three.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
  <link href="{{ asset('css/three.css') }}" rel="stylesheet"/>
{% endblock %}

{% block body %}
<canvas id="bg"></canvas>
  <main id="main" style="display: none">
     <header>
       <img id= "logo" src="{{ asset('logo.gif') }}" alt="pixelburger logo">
     </header>

     <blockquote>
       <p>Nasze inspiracje są zbudowane z pixeli</p>
     </blockquote>

     <section>
       <h2>📜 Działalność</h2>
       <p>
         Witaj w PixoBurgers. Najlepszych burgerach w mieście serwowanych w znajomym pixel artowym otoczeniu.
       </p>

       <p>
         Całe nasze menu jest inspirowane grafiką z lat 80 i 90 -- poczuj się u nas jak w domu.
       </p>

       <p>
         Nasze kanapki serwujemy w tematycznie urządzonych pokojach. Sprawdz je wszystkie!
       </p>

     </section>

     <section class="light" id="sectionDwa">
       <h2>👩🏽‍🚀 Obsługa</h2>

       <p>
         Aktualnie jesteśmy dostępni tylko na miejscu. Nie mamy dowozu. Przyjdz do nas a dostarczymy ci ucztę do stolika!
       </p>

       <h2>🏆 Nasz smak zwycięża!</h2>

       <p>
         Zgłodniałeś grając w ulubione gierki? Poczęstuj się naszymi bułami ich smak zwycięża!
       </p>

     </section>

     <div id="thanks">
       <a href="{{ path('rezerwacja3d') }}">
         <img id= "dziekujemy" src="{{ asset('svg/zarezerwuj.svg') }}" alt="Zarezerwuj stolik - już teraz!">
       </a>
     </div>

     <section class="left">
       <h1>Twórcy:</h1>

       <h3>🍔 Majewski Mateusz</h3>
       <p>
         nr albumu : 111443
       </p>
       <h3>🍔 Meyer Marek</h3>
       <p>
         nr albumu : 111521
       </p>
       <h3>🍔 Wachowicz Sebastian</h3>
       <p>
         nr albumu : 112376
       </p>

     </section>

     <div id="thanks">
       <img id= "dziekujemy" src="{{ asset('svg/dziekujemy.svg') }}" alt="dziekujemy za odwiedziny! zapraszamy ponownie!">
     </div>

   </main>
{% endblock %}

{% block javascripts %}
  <script type="module" src="{{ asset('js/main.js') }}"></script>
  <script>
    window.onload = function()
      { document.getElementById("main").style.display = ""; }
  </script>
{% endblock %}